"""Render the Asterisk configuration used by this application.

Only what the receptionist needs is enabled: AMI on localhost (call control and
readiness), the FastAGI dialplan, WAV playback, and one outbound interface - a PJSIP
trunk when SIP credentials are configured, or a chan_dongle GSM modem. ARI and the
built-in HTTP server are disabled. Secrets (AMI secret, SIP password) only appear in
the rendered files, which are written to a git-ignored directory.
"""
from __future__ import annotations

from pathlib import Path

NOLOAD_MODULES = [
    'chan_iax2.so', 'chan_skinny.so', 'chan_unistim.so', 'chan_mgcp.so', 'chan_motif.so', 'chan_ooh323.so',
    'chan_sip.so', 'chan_console.so', 'chan_alsa.so', 'chan_oss.so', 'chan_mobile.so',
    'res_ari.so', 'res_ari_applications.so', 'res_ari_asterisk.so', 'res_ari_bridges.so', 'res_ari_channels.so',
    'res_ari_device_states.so', 'res_ari_endpoints.so', 'res_ari_events.so', 'res_ari_mailboxes.so',
    'res_ari_model.so', 'res_ari_playbacks.so', 'res_ari_recordings.so', 'res_ari_sounds.so',
    'res_stasis_recording.so', 'res_stasis_playback.so', 'res_stasis_answer.so', 'res_stasis_snoop.so',
    'res_stasis_device_state.so', 'res_stasis_mailbox.so', 'res_http_websocket.so', 'res_phoneprov.so',
    'res_pjsip_phoneprov_provider.so', 'res_xmpp.so', 'res_calendar.so', 'res_fax.so', 'res_hep.so',
    'res_hep_pjsip.so', 'res_hep_rtcp.so', 'res_prometheus.so', 'res_snmp.so', 'res_config_ldap.so',
    'res_config_pgsql.so', 'res_config_odbc.so', 'res_odbc.so', 'cdr_adaptive_odbc.so', 'cdr_odbc.so',
    'app_voicemail.so', 'app_queue.so', 'app_confbridge.so', 'app_meetme.so', 'app_minivm.so',
    'res_parking.so', 'pbx_dundi.so', 'pbx_lua.so', 'pbx_ael.so', 'app_festival.so', 'res_speech.so',
]


def render(settings) -> dict[str, str]:
    """Return {filename: content} for /etc/asterisk."""
    s = settings
    cfg = s.resolve()
    endpoint = s.sip_trunk_endpoint
    files = {}
    files['asterisk.conf'] = (
        '; Generated by backend/app/telephony/asterisk_config.py\n'
        '[options]\nverbose = 3\ndebug = 0\nrunuser = asterisk\nrungroup = asterisk\n'
    )
    files['modules.conf'] = (
        '; Generated: autoload the core, disable modules the receptionist does not use.\n'
        '[modules]\nautoload = yes\n' + ''.join(f'noload => {m}\n' for m in NOLOAD_MODULES)
        + ('' if cfg.telephony_interface == 'gsm' else 'noload => chan_dongle.so\n')
    )
    files['manager.conf'] = (
        '; AMI: localhost only, one least-privilege user for the application.\n'
        '[general]\nenabled = yes\nwebenabled = no\nport = {port}\nbindaddr = 127.0.0.1\n'
        'displayconnects = no\nallowmultiplelogin = yes\ntimestampevents = yes\n\n'
        '[{user}]\nsecret = {secret}\ndeny = 0.0.0.0/0.0.0.0\npermit = 127.0.0.1/255.255.255.255\n'
        'read = system,call,command,config,reporting,dialplan,originate\n'
        'write = system,call,command,originate,reporting\nwritetimeout = 5000\n'
    ).format(port=s.asterisk_ami_port, user=s.asterisk_ami_username, secret=s.asterisk_ami_secret)
    files['http.conf'] = '; The built-in HTTP server (and therefore ARI) is not used.\n[general]\nenabled = no\n'
    files['ari.conf'] = '; ARI is not used: call control is AMI, the conversation is FastAGI.\n[general]\nenabled = no\n'
    files['extensions.conf'] = (
        '; Generated receptionist dialplan.\n'
        '[general]\nstatic = yes\nwriteprotect = yes\n\n'
        '[globals]\nMCS_AGI_HOST = {agi_host}\nMCS_AGI_PORT = {agi_port}\n\n'
        '[{context}]\n'
        '; Answered outbound calls (AMI Originate sets MCS_CALL_ID) and inbound calls.\n'
        'exten => s,1,NoOp(Mouth Care Solutions receptionist ${{MCS_CALL_ID}})\n'
        ' same => n,Answer()\n'
        ' same => n,AGI(agi://${{MCS_AGI_HOST}}:${{MCS_AGI_PORT}}/receptionist,${{MCS_CALL_ID}},'
        '${{IF($["${{MCS_DIRECTION}}" = ""]?inbound:${{MCS_DIRECTION}})}})\n'
        ' same => n,Hangup()\n\n'
        '[mouthcare-inbound]\n'
        '; Calls arriving from the trunk or modem.\n'
        'exten => _X.,1,Goto({context},s,1)\n'
        'exten => _+X.,1,Goto({context},s,1)\n'
        'exten => s,1,Goto({context},s,1)\n\n'
        '[default]\n; Nothing is reachable from the default context.\n'
    ).format(agi_host=s.asterisk_agi_host, agi_port=s.asterisk_agi_port, context=s.asterisk_context)
    pjsip = ('; Generated PJSIP configuration.\n'
             '[transport-udp]\ntype = transport\nprotocol = udp\nbind = 0.0.0.0:5060\n')
    if cfg.telephony_interface == 'sip' and s.sip_trunk_host:
        pjsip += (
            '\n[{ep}-auth]\ntype = auth\nauth_type = userpass\nusername = {user}\npassword = {password}\n'
            '\n[{ep}-aor]\ntype = aor\ncontact = sip:{host}\nqualify_frequency = 60\n'
            '\n[{ep}]\ntype = endpoint\ncontext = mouthcare-inbound\ndisallow = all\nallow = ulaw,alaw\n'
            'outbound_auth = {ep}-auth\naors = {ep}-aor\nfrom_user = {user}\nfrom_domain = {host}\n'
            'direct_media = no\nrtp_symmetric = yes\nforce_rport = yes\nrewrite_contact = yes\n'
            '\n[{ep}-identify]\ntype = identify\nendpoint = {ep}\nmatch = {host}\n'
        ).format(ep=endpoint, user=s.sip_trunk_username, password=s.sip_trunk_password, host=s.sip_trunk_host)
        if s.sip_trunk_requires_registration:
            pjsip += (
                '\n[{ep}-reg]\ntype = registration\noutbound_auth = {ep}-auth\nserver_uri = sip:{host}\n'
                'client_uri = sip:{user}@{host}\ncontact_user = {user}\nendpoint = {ep}\nretry_interval = 60\n'
                'forbidden_retry_interval = 600\n'
            ).format(ep=endpoint, user=s.sip_trunk_username, host=s.sip_trunk_host)
    files['pjsip.conf'] = pjsip
    if cfg.telephony_interface == 'gsm':
        files['dongle.conf'] = (
            '; chan_dongle (third-party module, build separately). The modem must be attached to WSL\n'
            '; with usbipd-win; set the data/audio ports reported by the modem.\n'
            '[general]\ninterval = 15\n\n[defaults]\ncontext = mouthcare-inbound\ngroup = 0\n'
            'rxgain = 0\ntxgain = 0\nautodeletesms = yes\nresetdongle = yes\nu2diag = -1\nusecallingpres = yes\n'
            'callingpres = allowed_passed_screen\ndisablesms = no\nlanguage = en\nsmsaspdu = yes\n'
            'mindtmfgap = 45\nmindtmfduration = 80\nmindtmfinterval = 200\ncallwaiting = auto\n'
            'disable = no\ninitstate = start\ndtmf = relax\n\n'
            '[{device}]\naudio = /dev/ttyUSB1\ndata = /dev/ttyUSB2\n'
        ).format(device=s.gsm_device)
    return files


def write(settings, target: Path) -> list[Path]:
    target.mkdir(parents=True, exist_ok=True)
    written = []
    for name, content in render(settings).items():
        path = target / name
        path.write_text(content, encoding='utf-8', newline='\n')
        written.append(path)
    return written
