CREATE EXTENSION IF NOT EXISTS vector;
CREATE TABLE clinic_config (key TEXT PRIMARY KEY, value JSONB NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE patients (id UUID PRIMARY KEY, name TEXT, phone TEXT, email TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE services (id TEXT PRIMARY KEY, name TEXT NOT NULL, approved BOOLEAN NOT NULL DEFAULT FALSE);
CREATE TABLE providers (id TEXT PRIMARY KEY, display_name TEXT, approved BOOLEAN NOT NULL DEFAULT FALSE);
CREATE TABLE appointments (id UUID PRIMARY KEY, booking_reference TEXT UNIQUE NOT NULL, patient_id UUID REFERENCES patients, service_id TEXT REFERENCES services, starts_at TIMESTAMPTZ NOT NULL, status TEXT NOT NULL, idempotency_key TEXT UNIQUE NOT NULL);
CREATE TABLE booking_holds (token TEXT PRIMARY KEY, slot_key TEXT UNIQUE NOT NULL, session_id TEXT NOT NULL, expires_at TIMESTAMPTZ NOT NULL);
CREATE TABLE conversations (id UUID PRIMARY KEY, channel TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE messages (id UUID PRIMARY KEY, conversation_id UUID REFERENCES conversations ON DELETE CASCADE, role TEXT, content TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE knowledge_documents (id UUID PRIMARY KEY, source TEXT, version TEXT, approval_status TEXT, effective_date DATE, locale TEXT);
CREATE TABLE knowledge_chunks (id UUID PRIMARY KEY, document_id UUID REFERENCES knowledge_documents ON DELETE CASCADE, content TEXT, category TEXT, embedding vector(1536));
CREATE TABLE usage_events (id UUID PRIMARY KEY, channel TEXT, provider TEXT, session_type TEXT, duration_seconds INT, billable_minutes NUMERIC, estimated_cost NUMERIC, outcome TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE admin_users (id UUID PRIMARY KEY, email TEXT UNIQUE, role TEXT NOT NULL);
CREATE TABLE audit_events (id UUID PRIMARY KEY, entity_type TEXT, entity_id TEXT, event_type TEXT, payload JSONB, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX appointments_time_idx ON appointments(starts_at);
CREATE INDEX knowledge_chunks_category_idx ON knowledge_chunks(category);
