import React, { useEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'
import { apiUrl } from './config'
import { NOW_WINDOW, callOutcomeMessage, callReadinessLabel, callRequestTarget, newId, readinessFromStatus, statusRows } from './callStatus'

const clinic = { phone: '+91 96423 40630', email: 'mouthcaresolutions@gmail.com', hours: 'Mon–Sat · 10:00 AM–8:00 PM' }
const quickPrompts = ['What are your clinic hours?', 'What services do you provide?', 'I want to book an appointment', 'I need a callback', 'I need urgent dental help']
const stamp = () => new Intl.DateTimeFormat('en-IN', { hour: 'numeric', minute: '2-digit' }).format(new Date())

function App() {
  const [messages, setMessages] = useState([{ id: 'welcome', role: 'assistant', text: 'Hello. I’m your Mouth Care Solutions receptionist. How can I help today?', time: stamp() }])
  const [input, setInput] = useState(''); const [busy, setBusy] = useState(false); const [voiceState, setVoiceState] = useState('idle'); const [call, setCall] = useState(null)
  const [slots, setSlots] = useState([]); const [selected, setSelected] = useState(null); const [callback, setCallback] = useState({ name: '', phone: '', window: '', topic: '', consent: false }); const [callBusy, setCallBusy] = useState(false); const [notice, setNotice] = useState('')
  const [mode, setMode] = useState('checking')
  const [runtime, setRuntime] = useState({ backend: 'checking', provider: 'checking', status: null, preflight: null })
  const bottom = useRef(null); const recognition = useRef(null)
  useEffect(() => bottom.current?.scrollIntoView({ behavior: 'smooth' }), [messages])
  useEffect(() => {
    // /api/status is cheap; live readiness is the server's cached full preflight (never computed here).
    const readJson = path => fetch(apiUrl(path)).then(response => response.ok ? response.json() : Promise.reject())
    const refresh = () => {
      readJson('/health')
        .then(health => setRuntime(current => ({ ...current, backend: health.status === 'ok' ? 'healthy' : 'unavailable' })))
        .catch(() => setRuntime(current => ({ ...current, backend: 'unavailable' })))
      readJson('/api/status')
        .then(status => {
          setMode(status.mode === 'live' ? 'live' : 'demo')
          const readiness = readinessFromStatus(status)
          setRuntime(current => ({ ...current, provider: status.telephony, status, preflight: readiness?.known ? readiness : null }))
        })
        .catch(() => setMode('offline'))
    }
    refresh()
    const timer = setInterval(refresh, 30000)
    return () => clearInterval(timer)
  }, [])
  const modeLabel = callReadinessLabel(mode, runtime.preflight)
  const blockers = runtime.preflight?.BLOCKERS || []
  async function send(text = input) { if (!text.trim() || busy) return; const user = { id: newId(), role: 'user', text: text.trim(), time: stamp() }; setInput(''); setMessages(m => [...m, user, { id: user.id + '-loading', role: 'assistant', text: '', loading: true, time: stamp() }]); setBusy(true)
    try { const r = await fetch(apiUrl('/api/agent/session'), { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ message: user.text, session_id: sessionStorage.getItem('mcs-session') || 'browser-demo' }) }); if (!r.ok) throw Error(); const d = await r.json(); if (d.session_id) sessionStorage.setItem('mcs-session', d.session_id); setMessages(m => [...m.filter(x => !x.loading), { id: user.id + '-answer', role: 'assistant', text: d.text || 'I’m sorry, I could not complete that request.', time: stamp(), slots: d.slots }]); if (d.slots) setSlots(d.slots) } catch { setMessages(m => [...m.filter(x => !x.loading), { id: user.id + '-error', role: 'assistant', text: 'The receptionist is temporarily unavailable. Please try again or request a callback.', time: stamp(), error: true }]) } finally { setBusy(false) } }
  function clearChat() { setMessages([{ id: newId(), role: 'assistant', text: 'Conversation cleared. How may I help?', time: stamp() }]) }
  function listen() { const SR = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SR) { setNotice('Browser voice is unavailable here. Text chat remains available.'); return } if (voiceState === 'listening') { recognition.current?.stop(); setVoiceState('idle'); return } const r = new SR(); recognition.current = r; r.lang = 'en-IN'; r.interimResults = true; r.onstart = () => setVoiceState('listening'); r.onresult = e => { const text = Array.from(e.results).map(x => x[0].transcript).join(''); setInput(text); if (e.results[0].isFinal) { setVoiceState('processing'); send(text) } }; r.onerror = () => { setVoiceState('idle'); setNotice('Microphone access failed. Please use text chat.'); }; r.onend = () => setVoiceState(s => s === 'listening' ? 'idle' : s); r.start() }
  async function loadSlots() { try { const r = await fetch(apiUrl('/api/slots')); if (r.status === 503) { setSlots([]); return setNotice('Live appointment availability is not connected. Ask the receptionist or request a callback and the clinic team will confirm a time.') } if (!r.ok) throw Error(); const d = await r.json(); setSlots(d.slots || []); setNotice(d.slots?.length ? 'Demo appointment times loaded.' : 'No appointment times are available.') } catch { setNotice('Appointments are temporarily unavailable.') } }
  async function requestCall(e) { e.preventDefault(); if (!callback.name || !callback.phone || !callback.consent) return setNotice('Please provide your name, phone number, and consent.') ; setCallBusy(true); const target = callRequestTarget(callback.window); const payload = target === '/api/callback' ? { patient_contact: callback.phone, topic: `${callback.name}: ${callback.topic || 'General assistance'}`, preferred_window: callback.window || 'To be arranged' } : { name: callback.name, patient_contact: callback.phone, preferred_window: 'Now', topic: callback.topic || 'General assistance', consent: callback.consent }; try { const r = await fetch(apiUrl(target), { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); const d = await r.json().catch(() => ({})); setNotice(callOutcomeMessage(r.status, d)); if (r.ok) setCall({ request_id: d.request_id || d.id, status: d.status, call_id: d.mode === 'live' ? d.call_id : undefined }) } catch { setNotice(callOutcomeMessage(0, null)) } finally { setCallBusy(false) } }
  return <div className="app"><header className="topbar"><div className="brand"><div className="mark">✦</div><div><strong>Mouth Care <span>Solutions</span></strong><small>AI RECEPTIONIST</small></div></div><nav><a href="#receptionist">Receptionist</a><a href="#appointments">Appointments</a><a href="#call">Call requests</a><a href="#clinic">Clinic info</a></nav><div className="status"><i /> {modeLabel}</div></header>
    <main><section className="hero"><div><p className="eyebrow">CALM SUPPORT · CLEAR NEXT STEPS</p><h1>Your care starts<br /><em>with a conversation.</em></h1><p className="lede">A thoughtful AI receptionist for Mouth Care Solutions—available to answer questions, help with appointments, and connect you with our team.</p><div className="hero-actions"><button className="primary" onClick={() => document.getElementById('message').focus()}>Start conversation <b>↗</b></button><button className="secondary" onClick={() => document.getElementById('call').scrollIntoView({ behavior: 'smooth' })}>Request a call</button></div></div><div className="hero-card"><div className="pulse"><span>✦</span></div><p className="eyebrow">RECEPTIONIST STATUS</p><h3>Here to help</h3><p>Ask about hours, services, or finding a convenient appointment.</p><div className="hours"><span>● Open today</span><b>{clinic.hours}</b></div></div></section>
      {notice && <div className="notice" role="status">{notice}<button onClick={() => setNotice('')}>×</button></div>}
      <div className="workspace"><section className="panel chat-panel" id="receptionist"><div className="panel-head"><div><p className="eyebrow">YOUR CONVERSATION</p><h2>Receptionist</h2></div><button className="text-btn" onClick={clearChat}>Clear conversation</button></div><div className="messages">{messages.map(m => <div className={`message ${m.role} ${m.error ? 'error' : ''}`} key={m.id}><div className="avatar">{m.role === 'assistant' ? '✦' : 'You'}</div><div><div className="bubble">{m.loading ? <span className="typing"><i /><i /><i /></span> : m.text}</div>{m.slots && <div className="inline-slots">{m.slots.map(s => <button key={s.id} className="slot-mini" onClick={() => { setSelected(s); document.getElementById('appointments').scrollIntoView({ behavior: 'smooth' }) }}>{new Date(s.starts_at).toLocaleString('en-IN', { weekday: 'short', hour: 'numeric', minute: '2-digit' })}</button>)}</div>}<time>{m.time}</time></div></div>)}<div ref={bottom} /></div><div className="quick">{quickPrompts.map(q => <button key={q} onClick={() => send(q)} disabled={busy}>{q}</button>)}</div><div className="composer"><button className={`mic ${voiceState === 'listening' ? 'active' : ''}`} onClick={listen} aria-label="Start browser voice">◉</button><input id="message" value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => e.key === 'Enter' && send()} placeholder="Ask anything about your visit…" disabled={busy} /><button className="send" onClick={() => send()} disabled={busy || !input.trim()}>↑</button></div><div className="voice-state">{voiceState === 'listening' ? 'Listening… speak naturally' : voiceState === 'processing' ? 'Processing your voice…' : 'Browser voice is separate from live phone service'}</div></section>
        <aside className="side"><section className="panel call-card" id="call"><div className="mode-tag">{modeLabel.toUpperCase()}</div><div className="call-icon">⌁</div><p className="eyebrow">PHONE RECEPTION</p><h2>Call the AI receptionist</h2><p>{mode === 'live' ? runtime.preflight?.LIVE_CALL_ALLOWED === true ? 'Ask the AI receptionist to call you now, or request a callback from the team.' : runtime.preflight ? 'Automated calls are not available yet. A team callback remains available.' : 'Checking live call readiness… A team callback remains available.' : 'Demo mode never places a real call; requests are recorded only.'}</p><dl className="status-list">{statusRows(runtime.backend, runtime.status).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{mode === 'live' && blockers.length > 0 && <details className="blockers"><summary>Why live calls are blocked ({blockers.length})</summary><ul>{blockers.map(b => <li key={b}>{b}</li>)}</ul></details>}<a className="clinic-phone" href={`tel:${clinic.phone.replace(/\D/g, '')}`}>{clinic.phone}</a><button className="outline full" onClick={() => { setCallback(c => ({ ...c, window: NOW_WINDOW })); document.getElementById('callback-form').scrollIntoView({ behavior: 'smooth' }) }}>Request a call <span>→</span></button>{call && <div className="call-result"><b>Request received</b><span>{call.request_id} · {call.status}</span></div>}</section>
          <section className="panel appointment" id="appointments"><div className="panel-head"><div><p className="eyebrow">FIND A TIME</p><h2>Appointments</h2></div><button className="text-btn" onClick={loadSlots}>Refresh</button></div>{slots.length ? <div className="slot-list">{slots.slice(0, 4).map(s => <button className={`slot-card ${selected?.id === s.id ? 'selected' : ''}`} key={s.id} onClick={() => setSelected(s)}><b>{new Date(s.starts_at).toLocaleDateString('en-IN', { weekday: 'short', day: 'numeric', month: 'short' })}</b><span>{new Date(s.starts_at).toLocaleTimeString('en-IN', { hour: 'numeric', minute: '2-digit' })}</span></button>)}</div> : <div className="empty-slots"><span>◷</span><p>Choose an appointment request in chat or load available times.</p><button className="text-btn" onClick={loadSlots}>Load times →</button></div>}{selected && <div className="selected-time">Selected: <b>{new Date(selected.starts_at).toLocaleString('en-IN')}</b></div>}</section></aside></div>
      <section className="lower-grid"><section className="panel callback" id="callback-form"><div className="panel-head"><div><p className="eyebrow">HUMAN SUPPORT</p><h2>Request a call</h2><p className="sub">Tell us when you’d like to hear from the team.</p></div><span className="form-number">01</span></div>{call ? <div className="success"><span>✓</span><h3>We’ve received your request</h3><p>Reference <b>{call.request_id}</b> · Status: {call.status}</p><small>{call.call_id ? 'The call has been handed to the clinic phone system. It is not considered connected until the phone network confirms it.' : 'Our team will use the requested window to follow up.'}</small></div> : <form onSubmit={requestCall}><div className="form-row"><label>Patient name<input value={callback.name} onChange={e => setCallback({ ...callback, name: e.target.value })} placeholder="Your name" /></label><label>Phone number<input value={callback.phone} onChange={e => setCallback({ ...callback, phone: e.target.value })} placeholder="+91…" /></label></div><div className="form-row"><label>Preferred time window<select value={callback.window} onChange={e => setCallback({ ...callback, window: e.target.value })}><option value="">Choose a window</option><option>{NOW_WINDOW}</option><option>Morning</option><option>Afternoon</option><option>Evening</option></select></label><label>What can we help with?<input value={callback.topic} onChange={e => setCallback({ ...callback, topic: e.target.value })} placeholder="Appointment, question…" /></label></div><label className="check"><input type="checkbox" checked={callback.consent} onChange={e => setCallback({ ...callback, consent: e.target.checked })} /> I consent to Mouth Care Solutions contacting me about this request, including an automated AI receptionist call when I choose “Now”. I can say “do not call me” at any time.</label><button className="primary" disabled={callBusy}>{callBusy ? 'Sending…' : 'Request a call  →'}</button></form>}</section><section className="panel clinic" id="clinic"><p className="eyebrow">MOUTH CARE SOLUTIONS</p><h2>Clinic information</h2><div className="info"><span>⌖</span><p>{'Door No. 29-28-23, Bhavani Complex, Suryaraopeta, Vijayawada, Andhra Pradesh 520002'}<br /><a href={`mailto:${clinic.email}`}>{clinic.email}</a></p></div><div className="info"><span>◷</span><p><b>{clinic.hours}</b><br />Sunday · Closed</p></div><div className="service-pills">{['Preventive', 'Restorative', 'Cosmetic', 'Orthodontic', 'Emergency care'].map(x => <span key={x}>{x}</span>)}</div></section></section></main><footer><b>Mouth Care Solutions</b><span>AI assistance does not replace professional clinical advice.</span><a href={`tel:${clinic.phone.replace(/\D/g, '')}`}>{clinic.phone}</a></footer></div>
}
createRoot(document.getElementById('root')).render(<App />)
