"""Generate the packaged telephone voice pack from the Fish Speech reference voice.

Run with the Fish Speech virtualenv (it provides httpx, ormsgpack, numpy and
faster-whisper):

    E:\\fish-speech\\.venv\\Scripts\\python.exe scripts/generate_voice_pack_http.py --publish

Every asset is generated by the running Fish Speech HTTP server (/v1/tts) using
the reference WAV and its transcript as in-context conditioning, converted to
8 kHz mono 16-bit PCM, and then verified:

* acoustic checks: plausible duration for the word count, real speech energy
  modulation (rejects constant tones and silence);
* ASR checks: a faster-whisper transcript must contain the asset keywords and
  stay within a word-error-rate bound of the canonical text.

Failed assets are regenerated with a new seed. Work is staged in
artifacts/voice-pack-staging and is only published to artifacts/voice-pack
(with a provenance manifest) when every asset passes. Re-running resumes: an
asset already verified for the same text, reference and parameters is reused.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
import shutil
import subprocess
import sys
import tempfile
import time
import wave
from datetime import datetime, timezone
from pathlib import Path

import httpx
import numpy as np
import ormsgpack

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
from backend.app.services.voice_pack import (  # noqa: E402  (stdlib-only module shared with the runtime validator)
    load_voice_pack,
    transcript_problems,
)

DEFAULT_REFERENCE = PROJECT_ROOT / "fish-references" / "mouth-care-receptionist-reference-20260919.wav"
REFERENCE_TEXT = (
    "Tomorrow is holiday because of Sunday. The Sunday is because of today is Saturday. "
    "Today is Saturday is because of yesterday is Friday. Friday is because of Thursday. "
    "But I know you are not willing to listen, but you have to listen."
)
GENERATION_PARAMS = {
    "chunk_length": 200,
    "max_new_tokens": 1024,
    "top_p": 0.7,
    "repetition_penalty": 1.2,
    "temperature": 0.7,
    "normalize": True,
}
BASE_SEED = 20260926
TELEPHONE_FILTER = (
    "silenceremove=start_periods=1:start_threshold=-50dB:start_silence=0.05,"
    "areverse,silenceremove=start_periods=1:start_threshold=-50dB:start_silence=0.05,areverse,"
    "highpass=f=90,lowpass=f=3600,loudnorm=I=-18:TP=-2:LRA=11,apad=pad_dur=0.25"
)
GENERATION_STATUS = "fish_http_reference_conditioned"
VALIDATION_STATUS = "asr_verified"

_DIGIT_WORDS = {
    "zero": "0", "oh": "0", "one": "1", "two": "2", "three": "3", "four": "4",
    "five": "5", "six": "6", "seven": "7", "eight": "8", "nine": "9",
}
_NUMBER_WORDS = set(_DIGIT_WORDS) | {
    "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen",
    "eighteen", "nineteen", "twenty", "thirty", "forty", "fifty", "sixty", "seventy",
    "eighty", "ninety", "hundred", "thousand", "plus", "am", "pm", "a", "m", "p",
}


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def fish_revision(fish_root: Path) -> dict:
    def git(*args: str) -> str:
        try:
            return subprocess.run(["git", "-C", str(fish_root), *args], capture_output=True, text=True, timeout=20).stdout
        except (OSError, subprocess.SubprocessError):
            return ""
    # Porcelain lines are "XY path"; the leading status column may be a space, so never strip it.
    modified = git("status", "--porcelain", "--untracked-files=no").splitlines()
    return {
        "version": git("describe", "--tags", "--always").strip(),
        "commit": git("rev-parse", "--short", "HEAD").strip(),
        "local_modifications": sorted(line[3:].strip() for line in modified if len(line) > 3),
    }


def tokens(text: str) -> list[str]:
    return re.findall(r"[a-z0-9']+", text.lower().replace("-", " "))


def content_words(words: list[str]) -> list[str]:
    return [w for w in words if not any(ch.isdigit() for ch in w) and w not in _NUMBER_WORDS]


def word_error_rate(reference: list[str], hypothesis: list[str]) -> float:
    if not reference:
        return 0.0 if not hypothesis else 1.0
    previous = list(range(len(hypothesis) + 1))
    for i, ref_word in enumerate(reference, 1):
        current = [i] + [0] * len(hypothesis)
        for j, hyp_word in enumerate(hypothesis, 1):
            current[j] = min(previous[j] + 1, current[j - 1] + 1, previous[j - 1] + (ref_word != hyp_word))
        previous = current
    return previous[-1] / len(reference)


def spoken_digits(text: str) -> str:
    """Collapse a transcript into its digit sequence ('plus nine one' / '+91' -> '91')."""
    out = []
    for word in tokens(text):
        if word.isdigit():
            out.append(word)
        elif word in _DIGIT_WORDS:
            out.append(_DIGIT_WORDS[word])
    return "".join(out)


def to_telephone_wav(raw: bytes, target: Path) -> None:
    source = target.with_suffix(".source.wav")
    source.write_bytes(raw)
    try:
        subprocess.run(
            ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-i", str(source),
             "-af", TELEPHONE_FILTER, "-ar", "8000", "-ac", "1", "-c:a", "pcm_s16le", str(target)],
            check=True, timeout=180,
        )
    finally:
        source.unlink(missing_ok=True)


def acoustic_report(path: Path, text: str) -> dict:
    with wave.open(str(path), "rb") as wav_file:
        sample_rate, channels, width, frames = (
            wav_file.getframerate(), wav_file.getnchannels(), wav_file.getsampwidth(), wav_file.getnframes())
        pcm = wav_file.readframes(frames)
    report = {"sample_rate": sample_rate, "channels": channels, "sample_width": width, "frames": frames,
              "duration_seconds": round(frames / sample_rate, 3) if sample_rate else 0.0}
    errors = []
    if (sample_rate, channels, width) != (8000, 1, 2) or frames <= 0:
        errors.append("telephone_format")
        report["errors"] = errors
        return report
    samples = np.frombuffer(pcm, dtype="<i2").astype(np.float64) / 32768.0
    window = int(sample_rate * 0.02)
    count = len(samples) // window
    rms = np.sqrt(np.mean(samples[: count * window].reshape(count, window) ** 2, axis=1)) if count else np.array([0.0])
    active = rms > 10 ** (-40 / 20)
    active_rms = rms[active]
    modulation = float(np.std(active_rms) / np.mean(active_rms)) if active_rms.size else 0.0
    word_count = len(tokens(text))
    duration = frames / sample_rate
    report.update({
        "word_count": word_count,
        "seconds_per_word": round(duration / max(1, word_count), 3),
        "active_fraction": round(float(active.mean()), 3),
        "energy_modulation": round(modulation, 3),
        "peak_dbfs": round(20 * math.log10(max(1e-9, float(np.max(np.abs(samples))))), 2),
    })
    if duration < 0.2 * word_count + 0.4:
        errors.append("too_short_for_text")
    if duration > 0.85 * word_count + 3.0:
        errors.append("too_long_for_text")
    if report["active_fraction"] < 0.35:
        errors.append("mostly_silent")
    if modulation < 0.3:
        errors.append("no_speech_modulation")
    report["errors"] = errors
    return report


class Transcriber:
    def __init__(self, model_name: str):
        from faster_whisper import WhisperModel
        self.model_name = model_name
        self.model = WhisperModel(model_name, device="cpu", compute_type="int8")

    def __call__(self, path: Path) -> str:
        segments, _ = self.model.transcribe(str(path), language="en", beam_size=5, vad_filter=False)
        return " ".join(segment.text.strip() for segment in segments).strip()


def character_error_rate(reference: list[str], hypothesis: list[str]) -> float:
    """Edit distance over the concatenated letters; tolerant of ASR word splits
    such as 'Vijaya Vada' for 'Vijayawada' while still catching wrong content."""
    return word_error_rate(list("".join(reference)), list("".join(hypothesis)))


def asr_report(transcript: str, prompt: dict, asset_id: str) -> dict:
    expected = prompt["text"]
    heard = tokens(transcript)
    reference_words, heard_words = content_words(tokens(expected)), content_words(heard)
    wer = word_error_rate(reference_words, heard_words)
    cer = character_error_rate(reference_words, heard_words)
    missing = [k for k in prompt.get("keywords", []) if not any(k in w for w in heard)]
    errors = []
    if missing:
        errors.append("keywords_missing:" + ",".join(missing))
    errors.extend(p for p in transcript_problems(transcript, prompt) if not p.startswith("asr_keywords_missing"))
    if wer > 0.35 and cer > 0.2:
        errors.append(f"transcript_mismatch:wer={wer:.2f},cer={cer:.2f}")
    report = {"transcript": transcript, "content_wer": round(wer, 3), "content_cer": round(cer, 3), "keywords_missing": missing}
    if asset_id == "clinic_phone":
        digits = spoken_digits(transcript)
        report["digits_heard"] = digits
        if digits != "919642340630":
            errors.append("phone_digits_mismatch")
    report["errors"] = errors
    return report


def generation_key(text: str, reference_sha: str, validation_version: int = 0) -> str:
    payload = json.dumps({"text": text, "reference": reference_sha, "reference_text": REFERENCE_TEXT,
                          "params": GENERATION_PARAMS, "filter": TELEPHONE_FILTER}, sort_keys=True)
    if validation_version:
        payload = json.dumps({"generation": json.loads(payload), "validation_version": validation_version}, sort_keys=True)
    return sha256_bytes(payload.encode())


def synthesize(client: httpx.Client, fish_url: str, text: str, reference: bytes, seed: int) -> bytes:
    request = {
        "text": text,
        "references": [{"audio": reference, "text": REFERENCE_TEXT}],
        "reference_id": None,
        "seed": seed,
        "use_memory_cache": "on",
        "format": "wav",
        "streaming": False,
        **GENERATION_PARAMS,
    }
    response = client.post(
        f"{fish_url.rstrip('/')}/v1/tts",
        params={"format": "msgpack"},
        content=ormsgpack.packb(request),
        headers={"content-type": "application/msgpack"},
    )
    response.raise_for_status()
    if not response.content.startswith(b"RIFF"):
        raise RuntimeError(f"fish_response_not_wav content_type={response.headers.get('content-type')}")
    return response.content


def load_state(path: Path) -> dict:
    if path.is_file():
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            pass
    return {"assets": {}}


def save_state(path: Path, state: dict) -> None:
    tmp = path.with_suffix(".tmp")
    tmp.write_text(json.dumps(state, indent=2) + "\n", encoding="utf-8")
    tmp.replace(path)


def publish(staging: Path, pack_dir: Path, state: dict, prompts: dict, reference: Path, fish: dict, asr_model: str) -> None:
    pack_dir.parent.mkdir(parents=True, exist_ok=True)
    publish_dir = Path(tempfile.mkdtemp(prefix=f"{pack_dir.name}.publish-", dir=pack_dir.parent))
    backup_dir = pack_dir.with_name(f"{pack_dir.name}.backup-{time.time_ns()}")
    assets = []
    try:
        for asset_id in prompts:
            entry = state["assets"][asset_id]
            target = publish_dir / f"{asset_id}.wav"
            shutil.copyfile(staging / f"{asset_id}.wav", target)
            asset_asr_model = entry.get("asr_model") or f"faster-whisper/{asr_model}"
            assets.append({
            "asset_id": asset_id,
            "intent": asset_id,
            "source_text": prompts[asset_id]["text"],
            "file_path": f"artifacts/voice-pack/{asset_id}.wav",
            "file_size": target.stat().st_size,
            "sha256": sha256_file(target),
            "raw_sha256": entry["raw_sha256"],
            "duration_seconds": entry["acoustic"]["duration_seconds"],
            "sample_rate": 8000,
            "channels": 1,
            "sample_width": 2,
            "frames": entry["acoustic"]["frames"],
            "seed": entry["seed"],
            "attempt": entry["attempt"],
            "generation_seconds": entry["generation_seconds"],
            "generated_at": entry["generated_at"],
            "generation_status": GENERATION_STATUS,
            "validation_status": VALIDATION_STATUS,
            "acoustic": {k: v for k, v in entry["acoustic"].items() if k != "errors"},
            "asr_model": asset_asr_model,
            "asr": {**{k: v for k, v in entry["asr"].items() if k != "errors"}, "model": asset_asr_model},
            })
        asr_models = sorted({asset["asr_model"] for asset in assets})
        manifest = {
        "pack_version": "2.0.0",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "generator": "scripts/generate_voice_pack_http.py",
        "fish_speech_model": "fish-speech-1.5",
        "fish_speech_version": fish["version"],
        "fish_speech_commit": fish["commit"],
        "fish_speech_local_modifications": fish["local_modifications"],
        "reference_audio_filename": reference.name,
        "reference_audio_sha256": sha256_file(reference),
        "reference_transcript": REFERENCE_TEXT,
        "generation_params": GENERATION_PARAMS,
        "telephone_filter": TELEPHONE_FILTER,
        "asr_model": asr_models[0] if len(asr_models) == 1 else "mixed",
        "asr_models": asr_models,
        "output_format": "pcm_s16le_wav",
        "sample_rate": 8000,
        "channels": 1,
        "sample_width": 2,
        "intent_mapping": {asset_id: f"{asset_id}.wav" for asset_id in prompts},
        "assets": assets,
        }
        manifest_tmp = publish_dir / "manifest.json.tmp"
        manifest_tmp.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
        manifest_tmp.replace(publish_dir / "manifest.json")
        validation = load_voice_pack(publish_dir, prompts, reference)
        if not validation.valid:
            raise RuntimeError("staged_voice_pack_invalid:" + ",".join(validation.errors[:8]))
        if pack_dir.exists():
            pack_dir.replace(backup_dir)
        try:
            publish_dir.replace(pack_dir)
        except OSError:
            if backup_dir.exists() and not pack_dir.exists():
                backup_dir.replace(pack_dir)
            raise
        if backup_dir.exists():
            shutil.rmtree(backup_dir)
    finally:
        if publish_dir.exists():
            shutil.rmtree(publish_dir)
        if backup_dir.exists() and not pack_dir.exists():
            backup_dir.replace(pack_dir)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--fish-url", default="http://127.0.0.1:8080")
    parser.add_argument("--fish-root", default=r"E:\fish-speech")
    parser.add_argument("--prompts", default=str(PROJECT_ROOT / "knowledge" / "clinic" / "voice_prompts.json"))
    parser.add_argument("--reference", default=str(DEFAULT_REFERENCE))
    parser.add_argument("--staging-dir", default=str(PROJECT_ROOT / "artifacts" / "voice-pack-staging"))
    parser.add_argument("--pack-dir", default=str(PROJECT_ROOT / "artifacts" / "voice-pack"))
    parser.add_argument("--only", nargs="*", help="asset ids to (re)generate")
    parser.add_argument("--max-attempts", type=int, default=3)
    parser.add_argument("--asr-model", default="small.en")
    parser.add_argument("--timeout", type=float, default=3600.0, help="per-request Fish timeout in seconds")
    parser.add_argument("--publish", action="store_true", help="publish to the pack dir when every asset is verified")
    args = parser.parse_args()

    prompts = json.loads(Path(args.prompts).read_text(encoding="utf-8"))["prompts"]
    reference = Path(args.reference)
    reference_bytes = reference.read_bytes()
    reference_sha = sha256_bytes(reference_bytes)
    staging = Path(args.staging_dir)
    staging.mkdir(parents=True, exist_ok=True)
    (staging / "raw").mkdir(exist_ok=True)
    state_path = staging / "state.json"
    state = load_state(state_path)
    prior_manifest_path = Path(args.pack_dir) / "manifest.json"
    if prior_manifest_path.is_file():
        try:
            prior_manifest = json.loads(prior_manifest_path.read_text(encoding="utf-8"))
            prior_entries = {entry["asset_id"]: entry for entry in prior_manifest.get("assets", [])}
            for asset_id, entry in prior_entries.items():
                previous = state["assets"].get(asset_id)
                if previous and not previous.get("asr_model"):
                    previous["asr_model"] = (entry.get("asr_model") or (entry.get("asr") or {}).get("model")
                                             or prior_manifest.get("asr_model"))
        except (OSError, ValueError, KeyError, TypeError):
            pass
    fish = fish_revision(Path(args.fish_root))
    selected = args.only or list(prompts)
    unknown = sorted(set(selected) - set(prompts))
    if unknown:
        parser.error(f"unknown asset ids: {unknown}")

    health = httpx.get(f"{args.fish_url.rstrip('/')}/v1/health", timeout=10)
    health.raise_for_status()
    print(f"FISH_HEALTH {health.status_code} {health.text.strip()} version={fish['version']} commit={fish['commit']}", flush=True)
    transcriber = Transcriber(args.asr_model)
    print(f"ASR_READY faster-whisper/{args.asr_model}", flush=True)

    with httpx.Client(timeout=httpx.Timeout(args.timeout, connect=10.0)) as client:
        for index, asset_id in enumerate(prompts):
            if asset_id not in selected:
                continue
            prompt = prompts[asset_id]
            key = generation_key(prompt["text"], reference_sha, prompt.get("validation_version", 0))
            previous = state["assets"].get(asset_id)
            staged = staging / f"{asset_id}.wav"
            if (previous and previous.get("key") == key and previous.get("status") == "verified"
                    and staged.is_file() and not args.only):
                # Re-check the existing take against the current rules before reusing it, so
                # tightened validation (e.g. a new required phrase) forces regeneration.
                recheck = asr_report(transcriber(staged), prompt, asset_id)
                acoustic_now = acoustic_report(staged, prompt["text"])
                if not recheck["errors"] and not acoustic_now["errors"]:
                    previous["asr"] = recheck
                    save_state(state_path, state)
                    print(f"SKIP {asset_id} re-verified heard={recheck['transcript']!r}", flush=True)
                    continue
                problems = recheck['errors'] + acoustic_now['errors']
                print(f"REVERIFY_FAIL {asset_id} {problems} heard={recheck['transcript']!r}", flush=True)
            attempts = []
            for attempt in range(1, args.max_attempts + 1):
                seed = BASE_SEED + index * 97 + (attempt - 1) * 1009
                started = time.perf_counter()
                print(f"GENERATE {asset_id} attempt={attempt} seed={seed} words={len(tokens(prompt['text']))}", flush=True)
                try:
                    raw = synthesize(client, args.fish_url, prompt["text"], reference_bytes, seed)
                except (httpx.HTTPError, RuntimeError) as exc:
                    attempts.append({"attempt": attempt, "seed": seed, "error": f"{type(exc).__name__}: {exc}"[:300]})
                    print(f"  FAIL request {type(exc).__name__}: {str(exc)[:200]}", flush=True)
                    continue
                elapsed = round(time.perf_counter() - started, 1)
                raw_path = staging / "raw" / f"{asset_id}.attempt{attempt}.wav"
                raw_path.write_bytes(raw)
                candidate = staging / f"{asset_id}.attempt{attempt}.wav"
                to_telephone_wav(raw, candidate)
                acoustic = acoustic_report(candidate, prompt["text"])
                asr = asr_report(transcriber(candidate), prompt, asset_id)
                errors = acoustic["errors"] + asr["errors"]
                result = {
                    "attempt": attempt, "seed": seed, "generation_seconds": elapsed,
                    "raw_sha256": sha256_bytes(raw), "acoustic": acoustic, "asr": asr, "errors": errors,
                }
                attempts.append(result)
                print(f"  {'PASS' if not errors else 'FAIL'} {elapsed}s dur={acoustic['duration_seconds']}s "
                      f"mod={acoustic.get('energy_modulation')} wer={asr['content_wer']} heard={asr['transcript']!r} {errors}",
                      flush=True)
                if not errors:
                    shutil.move(candidate, staging / f"{asset_id}.wav")
                    state["assets"][asset_id] = {
                        "key": key, "status": "verified", "text": prompt["text"],
                        "asr_model": f"faster-whisper/{args.asr_model}",
                        "generated_at": datetime.now(timezone.utc).isoformat(), **result, "attempts": attempts,
                    }
                    break
                candidate.unlink(missing_ok=True)
            else:
                state["assets"][asset_id] = {"key": key, "status": "failed", "text": prompt["text"], "attempts": attempts}
            save_state(state_path, state)

    verified = [a for a in prompts if state["assets"].get(a, {}).get("status") == "verified"
                and state["assets"][a].get("key") == generation_key(
                    prompts[a]["text"], reference_sha, prompts[a].get("validation_version", 0))]
    failed = [a for a in prompts if a not in verified]
    print(f"SUMMARY verified={len(verified)}/{len(prompts)} failed={failed}", flush=True)
    if failed:
        print("NOT_PUBLISHED: every asset must be verified before the pack is replaced", flush=True)
        return 1
    if args.publish:
        publish(staging, Path(args.pack_dir), state, prompts, reference, fish, args.asr_model)
        print(f"PUBLISHED {args.pack_dir}", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
