"""Fish Speech text-to-speech service for phone calls.

Fish Speech is the only speech source. For every utterance the service uses, in order:

1. the **voice pack** - approved receptionist utterances pre-generated by Fish Speech from
   the configured reference voice and verified (hash, reference, ASR) before use;
2. the **phrase cache** - earlier Fish Speech output for the same text *and the same voice
   signature* (model, version, reference audio hash, reference text, generation params);
3. **live Fish Speech synthesis**, sentence by sentence (streaming when enabled), only when
   ``FISH_SPEECH_LIVE_SYNTHESIS=true``. It is off by default because the measured CPU
   real-time factor on the development host (~14-17x) cannot serve a live phone turn.

Audio is converted to telephone PCM (16-bit signed little-endian mono PCM at
the stream rate). There is no other TTS engine and no hidden fallback: when none of the
above can produce audio, :class:`TtsUnavailable` is raised and the caller hears the
pre-generated Fish Speech ``technical_issue`` asset.
"""
from __future__ import annotations

import asyncio
import hashlib
import json
import logging
import re
import threading
import time
from collections.abc import AsyncIterator, Callable
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from ..services.voice_pack import VoicePackStatus
from .audio_adapter import AudioFormat, StreamingPcmConverter, convert_pcm, decode_wav, encode_wav
from .fish_speech import FishSpeechClient, FishSpeechError

logger = logging.getLogger(__name__)
FALLBACK_ASSET = 'technical_issue'
_SENTENCE = re.compile(r'(?<=[.!?])\s+(?=[A-Z0-9"\'])')


class TtsUnavailable(RuntimeError):
    def __init__(self, reason: str):
        super().__init__(reason)
        self.reason = reason


@dataclass(frozen=True)
class Utterance:
    text: str
    prompt_id: str | None = None


@dataclass
class TtsStats:
    source: str = ''            # voice_pack | phrase_cache | fish_live
    first_audio_ms: int | None = None
    synthesis_ms: int | None = None


def split_sentences(text: str, max_chars: int = 180) -> list[str]:
    """Sentence chunks for incremental synthesis; long sentences split at commas."""
    chunks: list[str] = []
    for sentence in (s.strip() for s in _SENTENCE.split(text.strip()) if s.strip()):
        while len(sentence) > max_chars:
            cut = sentence.rfind(',', 0, max_chars)
            cut = cut + 1 if cut > max_chars // 3 else max_chars
            chunks.append(sentence[:cut].strip())
            sentence = sentence[cut:].strip()
        if sentence:
            chunks.append(sentence)
    return chunks


class PhraseCache:
    """Disk cache of Fish Speech output keyed by text + voice signature."""

    def __init__(self, directory: Path):
        self.directory = directory

    @staticmethod
    def normalize(text: str) -> str:
        return re.sub(r'\s+', ' ', text).strip()

    def key(self, text: str, signature: dict) -> str:
        blob = json.dumps({'text': self.normalize(text), 'voice': signature}, sort_keys=True)
        return hashlib.sha256(blob.encode('utf-8')).hexdigest()

    def get(self, text: str, signature: dict) -> tuple[AudioFormat, bytes] | None:
        key = self.key(text, signature)
        meta_path, wav_path = self.directory / f'{key}.json', self.directory / f'{key}.wav'
        try:
            meta = json.loads(meta_path.read_text(encoding='utf-8'))
            if meta.get('voice') != signature or meta.get('text') != self.normalize(text):
                return None   # never serve audio made with a different voice/reference/model
            if hashlib.sha256(wav_path.read_bytes()).hexdigest() != meta.get('wav_sha256'):
                return None
            return decode_wav(wav_path.read_bytes())
        except (OSError, ValueError):
            return None

    def put(self, text: str, signature: dict, fmt: AudioFormat, pcm: bytes) -> None:
        key = self.key(text, signature)
        self.directory.mkdir(parents=True, exist_ok=True)
        wav = encode_wav(pcm, fmt)
        tmp = self.directory / f'{key}.wav.tmp'
        tmp.write_bytes(wav)
        tmp.replace(self.directory / f'{key}.wav')
        meta = {'text': self.normalize(text), 'voice': signature, 'wav_sha256': hashlib.sha256(wav).hexdigest(),
                'sample_rate': fmt.sample_rate, 'audio_seconds': round(fmt.duration_seconds(pcm), 3),
                'created_at': datetime.now(timezone.utc).isoformat()}
        (self.directory / f'{key}.json').write_text(json.dumps(meta, indent=2), encoding='utf-8')


class FishSpeechTTS:
    def __init__(self, *, client: FishSpeechClient, voice_pack: Callable[[], VoicePackStatus], cache: PhraseCache,
                 target: AudioFormat, live_synthesis: bool = False, streaming: bool = False,
                 first_audio_budget_seconds: float = 4.0):
        self.client = client
        self.voice_pack = voice_pack
        self.cache = cache
        self.target = target
        self.live_synthesis = live_synthesis
        self.streaming = streaming
        self.first_audio_budget_seconds = first_audio_budget_seconds
        self._converted: dict[tuple[str, int], bytes] = {}
        self._lock = threading.Lock()

    # Voice pack ---------------------------------------------------------------------------
    def asset_pcm(self, prompt_id: str) -> bytes | None:
        """Verified voice-pack asset in the stream format (converted once, then memoized)."""
        asset = self.voice_pack().assets.get(prompt_id)
        if asset is None:
            return None
        key = (asset.sha256, self.target.sample_rate)
        with self._lock:
            cached = self._converted.get(key)
        if cached is None:
            fmt, pcm = decode_wav(asset.content)
            cached = convert_pcm(pcm, fmt, self.target)
            with self._lock:
                self._converted[key] = cached
        return cached

    def warm(self) -> int:
        """Pre-convert every verified asset so the first word of a call has no conversion delay."""
        return sum(1 for prompt_id in list(self.voice_pack().assets) if self.asset_pcm(prompt_id) is not None)

    def fallback_pcm(self) -> bytes | None:
        return self.asset_pcm(FALLBACK_ASSET)

    def can_speak(self, utterance: Utterance) -> bool:
        if utterance.prompt_id and utterance.prompt_id in self.voice_pack().assets:
            return True
        if self.live_synthesis:
            return True
        signature = self.client.voice_signature()
        return all(self.cache.get(s, signature) is not None for s in split_sentences(utterance.text))

    # Audio for an utterance -------------------------------------------------------------------
    async def audio(self, utterance: Utterance, stats: TtsStats | None = None) -> AsyncIterator[bytes]:
        stats = stats if stats is not None else TtsStats()
        started = time.perf_counter()
        if utterance.prompt_id:
            pcm = await asyncio.to_thread(self.asset_pcm, utterance.prompt_id)
            if pcm is not None:
                elapsed_ms = int((time.perf_counter() - started) * 1000)
                stats.source, stats.first_audio_ms, stats.synthesis_ms = 'voice_pack', elapsed_ms, 0
                yield pcm
                return
        signature = self.client.voice_signature()
        sentences = split_sentences(utterance.text)
        cached = [await asyncio.to_thread(self.cache.get, s, signature) for s in sentences]
        if not sentences or (not self.live_synthesis and any(c is None for c in cached)):
            # Never start speaking an utterance that cannot be finished in the Fish voice.
            raise TtsUnavailable('not_in_voice_pack_and_live_synthesis_disabled')
        stats.source = 'phrase_cache' if all(c is not None for c in cached) else 'fish_live'
        for sentence, hit in zip(sentences, cached, strict=True):
            if hit is not None:
                fmt, pcm = hit
                converted = await asyncio.to_thread(convert_pcm, pcm, fmt, self.target)
                if stats.first_audio_ms is None:
                    stats.first_audio_ms = int((time.perf_counter() - started) * 1000)
                yield converted
                continue
            async for pcm in self._live(sentence, signature, stats, started, first=stats.first_audio_ms is None):
                yield pcm
        stats.synthesis_ms = int((time.perf_counter() - started) * 1000)

    async def _live(self, sentence: str, signature: dict, stats: TtsStats, started: float, *,
                    first: bool) -> AsyncIterator[bytes]:
        """Live Fish Speech synthesis of one sentence, cached afterwards.

        The first audio of an utterance must arrive within ``first_audio_budget_seconds``;
        otherwise the turn fails over to the pre-generated technical-issue asset.
        """
        budget = self.first_audio_budget_seconds if first else None
        collected: list[bytes] = []
        fmt: AudioFormat | None = None
        try:
            if self.streaming:
                converter: StreamingPcmConverter | None = None
                stream = self.client.stream(sentence)
                try:
                    while True:
                        try:
                            chunk_fmt, chunk = await (asyncio.wait_for(anext(stream), budget) if budget else anext(stream))
                        except StopAsyncIteration:
                            break
                        budget = None
                        fmt = chunk_fmt
                        collected.append(chunk)
                        converter = converter or StreamingPcmConverter(chunk_fmt, self.target)
                        out = converter.push(chunk)
                        if stats.first_audio_ms is None:
                            stats.first_audio_ms = int((time.perf_counter() - started) * 1000)
                        if out:
                            yield out
                finally:
                    await stream.aclose()
                if converter is not None:
                    tail = converter.flush()
                    if tail:
                        yield tail
            else:
                synthesis = self.client.synthesize(sentence)
                result = await (asyncio.wait_for(synthesis, budget) if budget else synthesis)
                fmt = result.fmt
                collected.append(result.pcm)
                if stats.first_audio_ms is None:
                    stats.first_audio_ms = int((time.perf_counter() - started) * 1000)
                yield await asyncio.to_thread(convert_pcm, result.pcm, result.fmt, self.target)
        except asyncio.TimeoutError as exc:
            raise TtsUnavailable('fish_speech_first_audio_budget_exceeded') from exc
        except FishSpeechError as exc:
            raise TtsUnavailable(f'fish_speech_{exc.code}') from exc
        if fmt is not None and collected:
            try:
                await asyncio.to_thread(self.cache.put, sentence, signature, fmt, b''.join(collected))
            except OSError:
                logger.warning('tts_cache_write_failed')
